os:
  - linux
language: node_js
node_js:
  - "10.15.3"
#cache:
#  directories:
#    - $HOME/.yarn-cache
#    - node_modules
before_install:
    # Update NPM
    - npm install -g npm
install:
  - npm prune
  - npm install
  - npm link
  - npm run coveralls
