os:
  - linux
language: node_js
node_js:
  - '10.16.1'
#cache:
#  directories:
#    - node_modules
before_install:
    # Update NPM
    - npm install -g npm
install:
#  - npm prune
  - npm install
  - npm link
  - npm run coveralls
