os:
  - linux
language: node_js
node_js:
  - "8.9.1"
cache:
  yarn: true
  directories:
#    - $HOME/.yarn-cache
#    - node_modules
before_install:
#  - npm -g i yo bower gulp-cli
  - yarn global add yo bower gulp-cli
install:
#  - npm prune
#  - npm install
#  - npm link
#  - npm run coveralls
  - yarn install
  - yarn link
  - yarn run coveralls
