os:
    - linux
language: node_js
node_js:
  - "6.9.0"
cache:
  yarn: true
  directories:
    - $HOME/.yarn-cache
    - node_modules
before_install:
  - yarn global add yo bower gulp-cli
install:
#  - npm prune
#  - npm install
#  - npm link
#  - npm run coveralls
  - yarn install
  - yarn link
#  - yarn run test
  - yarn run coveralls
