name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you for reporting your first issue. My master will take a look at his earliest convenience. - GitHub Bot'
        pr-message: 'Thank you for submitting your first PR. My master will take a look at his earliest convenience. - GitHub Bot'
