name: Semantic Release

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  create:
    branches: [ main, develop ]

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.2
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2.5.0
        with:
          semantic_version: 17.1.1
          branches: |
            [
              '+([0-9])?(.{+([0-9]),x}).x',
              'main',
              'develop',
              'next',
              'next-major',
              {
                name: 'beta',
                prerelease: true
              },
              {
                name: 'alpha',
                prerelease: true
              }
            ]
          dry_run: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: New release published
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          echo ${{ steps.semantic.outputs.new_release_version }}
          echo ${{ steps.semantic.outputs.new_release_major_version }}
          echo ${{ steps.semantic.outputs.new_release_minor_version }}
          echo ${{ steps.semantic.outputs.new_release_patch_version }}
